# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33d2713ac73803fae21ab3c3c984b1c7054f6469f5968373775adc93a30900abe21ef0ebee2142fbde824652d7123befbee1b2686c2c8a9711b742444911029

test:
  secret_key_base: 500bbb57e38dafbcdb57a4fb284cebc6775e13f5307c21bd16763e07ef16dfd4233ed9a481923fa4f226d40fbb290a6dd6e17a5927d5d50ecede73b944a406a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
